### ISSUE TITLE
"The format "PNG" is either not supported or the file is damaged"

### ISSUE THREAD

**Issue by xDiglett** [coldume/imagecraft#13]
When trying to upload a .png file using the following code:
```php
$builder = new ImageBuilder();
$layer = $builder->addBackgroundLayer();
$layer->filename('uploads/'.$fullname);
$layer->resize(300, 300, 'shrink');
$image = $builder->save();

if ($image->isValid()) {
// upload.
} else {
$reponse[] = ['c' => 1, 'error' => $image->getMessage()];
}
```
$image->getMessage() then returns:
__The format "PNG" is either not supported or the file is damaged. Server supports , "PNG", "JPEG", "GIF".__

I'm uploading the following image:
![Image](http://i.imgur.com/kGs2U6G.png)

When I try other images it works fine however. I'm trying to figure out why this one isn't working.

**Comment by stevecoug** [comment]
I'm getting the same error with some PNG files. It works with other PNG files, though. This file does not work:

![screenshot_2016-02-19-11-31-50](https://cloud.githubusercontent.com/assets/432808/13186994/f6ff4cda-d705-11e5-9df8-7889d39242d6.png)
