### ISSUE TITLE
FadeIn-FadeOut Layer

### ISSUE THREAD

**Issue by alvaro-octal** [coldume/imagecraft#16]
Hi, 

I not beging able to find a way to place a text layer which appears and disappears, is it possible?

thanks in advance.

Edit: this is what I'm trying to do, as you can see I would like to emulate the fadeout (transparency) with the numbers (505, 750, ....).
![Octal](https://meriland.es/usuario/firma/1/Octal.gif)

**Comment by coldume** [comment]
I'm afraid it is not possible using Imagecraft... If you are using this image on a website, maybe you can use JavaScript to achieve this effect.

**Comment by alvaro-octal** [comment]
I really would prefer to generate the "full" gif automatically, how difficult would it be to expand the library in order to add this kind of functionality?

None that I'm not even familiar with PHP-GD or GIF behavior, so I'm asking without any knowledge about the difficulty.

**Comment by coldume** [comment]
-   Imagecraft or PHP GD cannot do this, it is not the problem about the difficulty, it is simply impossible. 
-   However, you can do this with [ImageMagick cmd](http://www.imagemagick.org/Usage/anim_mods/) and probably [ImageMagick PHP extension](http://php.net/manual/en/book.imagick.php), although the learning curve is very deep, you could post your question over the [ImageMagick forum](http://www.imagemagick.org/discourse-server/viewforum.php?f=1), people there are very friendly and helpful.
-   Use animated SVG. (I have no experience with it, so I'm not sure)
