### ISSUE TITLE
PNG as Background, Gif as center piece.

### ISSUE THREAD

**Issue by bubamacko** [coldume/imagecraft#17]
Hello! Im trying this library (Awesome btw). I use to put a frame into some images for a pet project.
Now im try to pute a frame into a gif but i cant seems to do it.
Any ideas?

**Comment by coldume** [comment]
Unfortunately, you cannot use animated GIF as a layer, otherwise it will lose animation. Please see https://github.com/coldume/gd-enhancer/issues/12
