### ISSUE TITLE
Shrinking transparent GIF images

### ISSUE THREAD

**Issue by Crypton33** [coldume/imagecraft#5]
Hello,
I've found out that there are artifacts after resizing a gif image with an alpha channel.

Before resizing:
![Before](http://vestia.pl/images/uploader/30032015-5814041.gif)

After resizing:
![After](http://vestia.pl/images/uploader/30032015-3353655.gif)

It can't be seen on white background, but you can right click on second image and then click "show image in new tab".

Is there something I can do with it?

**Comment by coldume** [comment]
Hi, I have tested this image on my own machine and have no such issue. Maybe your GD lib is out of date, try it on different server may resolve your issue. 

Feel free to ask me if you have any other issue, thanks!
