### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by IProSoft** [coldume/imagecraft#6]
Hi

Is there any extended documentation, with info about functions, etc ?

Also is there way to add transparency to layer ?

Regards

**Comment by coldume** [comment]
Sorry, there is no extended documentation available, as it is just a simple library, in the readme, the examples cover almost all the methods and you can find information from Layers Methods section (let you mouse hover the "message" icons).

If I understand you question correctly, Imagecraft preserve image transparency automatically, you don't have to add transparency manually.
