### ISSUE TITLE
animated gifs - hardcoded frame limit of 50?

### ISSUE THREAD

**Issue by FeuerSturm91** [coldume/imagecraft#8]
Hi,
first of all, thanks for this awesome work!

I've encountered a problem though:
I'm using ImageCraft to add a partitally transparent PNG image
to an animated GIF, it work perfect for any GIF between 2 and 50 frames, 
but whenever I'm using an animated GIF with more than 50 frames, the finished
image is just the added PNG, the GIF "background" image is missing.

Is there a hard coded limit of 50 frames?

Thanks in advance!

**Comment by coldume** [comment]
You mean the PNG watermark lost its transparency? If so, yes, it is intended. Imagecraft has two mode for animated GIF, the high quality mode and low quality mode, when the GIF image is considered too big (too many frames or dimensions are too large), Imagecraft will fall back to low quality mode or "protection" mode, see [this](https://github.com/coldume/imagecraft/blob/develop/src/Engine/PhpGd/Extension/Gif/ImageFactory.php#L151). The reason for this is that PHP has its memory limit and PHP is not that good at manipulating images. Without this protection, when a GIF image is too big, it will take a very long time to finish the manipulation and it has a high chance to crash your server.

If you want to fix this, my suggestion is to switch to another library like imagemagick or its cli tools, or even  another language, nodejs or golang is a good choice, they are 100x faster than PHP. Anyway, thanks for reporting this, if you find any other issues, feel free to post here. Thanks.

**Comment by FeuerSturm91** [comment]
Hi coldume,
thanks for your reply, the line of code you linked explained why it's not working like expected for me:
The GIFs are 468x100pixels, so anything above 51 frames (= 2 386 800 pixels) would be larger than the pixel limit you set.....

Unfortunately, due to several reasons, I'm bound to PHP, so I have to try to increase that limit a bit......
